### ISSUE TITLE
UI redefinition

### ISSUE THREAD

**Issue by Renanse** [flufy3d/UEWebSocket#1]
Hi there! I am curious if you have this working yet?  I need to use websockets in UE4 and have been having issues getting around including libraries that include OpenSSL - I end up getting errors like:

>C2365	'UI': redefinition; previous definition was 'namespace'	
..\UE_4.15\Engine\Source\ThirdParty\OpenSSL\1.0.2g\include\Win64\VS2015\openssl\ossl_typ.h

**Comment by flufy3d** [comment]
hello renanse ,I have not used  the OpenSSL in my plugin
